# Generated by Django 5.1.6 on 2025-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_video_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
