# Generated by Django 5.1.6 on 2025-03-04 19:06

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_video_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='html',
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
